export const topics = [
  {
    questions: 10,
    value: 'aging_101',
    name: 'Introduction to Aging',
    subject: 'Aging',
  },
  {
    value: 'anesthesia_basics',
    name: 'Basics of Anesthesiology',
    questions: 10,
    subject: 'Anesthesio­logy',
  },
  {
    value: 'biochem_reactions',
    name: 'Biochemical Reactions',
    questions: 10,
    subject: 'Biochemistry',
  },
  {
    value: 'cardio_system',
    name: 'Cardiovascular System Overview',
    questions: 10,
    subject: 'Cardiology',
  },
  {
    value: 'clinical_ethics_intro',
    name: 'Introduction to Clinical Ethics',
    questions: 10,
    subject: 'Clinical Ethics',
  },
  {
    value: 'history_taking',
    name: 'History Taking Skills',
    questions: 10,
    subject: 'Clinical Skills',
  },
  {
    value: 'ventilation_basics',
    name: 'Ventilator Basics in Critical Care',
    questions: 10,
    subject: 'Critical Care',
  },
  {
    value: 'deib_principles',
    name: 'Core Principles of DEIB',
    questions: 10,
    subject: 'DEIB',
  },
  {
    value: 'dose_calc',
    name: 'Introduction to Dosage Calculation',
    questions: 10,
    subject: 'Dosage Calculation',
  },
  {
    value: 'embryo_dev',
    name: 'Embryo Development Stages',
    questions: 10,
    subject: 'Embryology',
  },
  {
    value: 'er_protocols',
    name: 'Emergency Room Protocols',
    questions: 10,
    subject: 'Emergency Medicine',
  },
  {
    value: 'family_practice',
    name: 'Essentials of Family Medicine',
    questions: 10,
    subject: 'Family Medicine',
  },
  {
    value: 'gastro_disorders',
    name: 'Common Gastrointestinal Disorders',
    questions: 10,
    subject: 'Gastro­enterology',
  },
  {
    value: 'aging_disorders',
    name: 'Disorders of Aging',
    questions: 10,
    subject: 'Gerontology',
  },
  {
    value: 'healthcare_tech',
    name: 'Technology in Healthcare Informatics',
    questions: 10,
    subject: 'Healthcare Informatics',
  },
  {
    value: 'maternal_care',
    name: 'Maternal Health and Care',
    questions: 10,
    subject: 'Maternity + Childbearing Family',
  },
  {
    value: 'genetic_testing',
    name: 'Genetic Testing in Medicine',
    questions: 10,
    subject: 'Medical Genetics',
  },
  {
    value: 'nursing_models',
    name: 'Theoretical Models in Nursing',
    questions: 10,
    subject: 'Nursing Theory',
  },
  {
    questions: 10,
    value: 'aging_psych',
    name: 'Psychology of Aging',
    subject: 'Aging',
  },
  {
    value: 'anesthesia_risks',
    name: 'Risks in Anesthesiology',
    questions: 10,
    subject: 'Anesthesio­logy',
  },
  {
    value: 'protein_structures',
    name: 'Protein Structures in Biochemistry',
    questions: 10,
    subject: 'Biochemistry',
  },
  {
    value: 'heart_diseases',
    name: 'Heart Diseases Overview',
    questions: 10,
    subject: 'Cardiology',
  },
  {
    value: 'ethics_dilemmas',
    name: 'Ethical Dilemmas in Medicine',
    questions: 10,
    subject: 'Clinical Ethics',
  },
  {
    value: 'exam_techniques',
    name: 'Physical Exam Techniques',
    questions: 10,
    subject: 'Clinical Skills',
  },
  {
    value: 'shock_treatment',
    name: 'Treatment of Shock in Critical Care',
    questions: 10,
    subject: 'Critical Care',
  },
  {
    value: 'deib_in_practice',
    name: 'Implementing DEIB in Healthcare',
    questions: 10,
    subject: 'DEIB',
  },
  {
    value: 'calc_pediatrics',
    name: 'Dosage Calculation for Pediatrics',
    questions: 10,
    subject: 'Dosage Calculation',
  },
  {
    value: 'fetal_dev',
    name: 'Fetal Development and Health',
    questions: 10,
    subject: 'Embryology',
  },
  {
    value: 'trauma_mgmt',
    name: 'Trauma Management in the ER',
    questions: 10,
    subject: 'Emergency Medicine',
  },
  {
    value: 'family_prevention',
    name: 'Preventative Care in Family Medicine',
    questions: 10,
    subject: 'Family Medicine',
  },
  {
    value: 'gi_procedures',
    name: 'Diagnostic Procedures in Gastro­enterology',
    questions: 10,
    subject: 'Gastro­enterology',
  },
  {
    value: 'geriatric_care',
    name: 'Care for the Elderly',
    questions: 10,
    subject: 'Gerontology',
  },
  {
    value: 'informatics_security',
    name: 'Data Security in Healthcare Informatics',
    questions: 10,
    subject: 'Healthcare Informatics',
  },
  {
    value: 'childbirth_techniques',
    name: 'Modern Childbirth Techniques',
    questions: 10,
    subject: 'Maternity + Childbearing Family',
  },
  {
    value: 'gene_therapy',
    name: 'Gene Therapy Approaches',
    questions: 10,
    subject: 'Medical Genetics',
  },
  {
    value: 'nursing_philosophy',
    name: 'Philosophy of Nursing',
    questions: 10,
    subject: 'Nursing Theory',
  },
  {
    questions: 10,
    value: 'aging_bio',
    name: 'Biology of Aging',
    subject: 'Aging',
  },
  {
    value: 'anesthesia_methods',
    name: 'Methods in Anesthesiology',
    questions: 10,
    subject: 'Anesthesio­logy',
  },
  {
    value: 'enzymes_role',
    name: 'Role of Enzymes in Biochemistry',
    questions: 10,
    subject: 'Biochemistry',
  },
  {
    value: 'cardio_rehab',
    name: 'Cardiac Rehabilitation Programs',
    questions: 10,
    subject: 'Cardiology',
  },
  {
    value: 'clinical_confidentiality',
    name: 'Maintaining Confidentiality',
    questions: 10,
    subject: 'Clinical Ethics',
  },
  {
    value: 'communication_skills',
    name: 'Patient Communication Skills',
    questions: 10,
    subject: 'Clinical Skills',
  },
  {
    value: 'icu_challenges',
    name: 'Challenges in the ICU',
    questions: 10,
    subject: 'Critical Care',
  },
  {
    value: 'deib_frameworks',
    name: 'DEIB Frameworks for Diversity',
    questions: 10,
    subject: 'DEIB',
  },
  {
    value: 'calc_iv_drips',
    name: 'IV Drip Dosage Calculations',
    questions: 10,
    subject: 'Dosage Calculation',
  },
  {
    value: 'prenatal_health',
    name: 'Prenatal Health Guidelines',
    questions: 10,
    subject: 'Embryology',
  },
  {
    value: 'emergency_triage',
    name: 'Triage Protocols in Emergency Medicine',
    questions: 10,
    subject: 'Emergency Medicine',
  },
  {
    value: 'rural_healthcare',
    name: 'Family Medicine in Rural Areas',
    questions: 10,
    subject: 'Family Medicine',
  },
  {
    value: 'liver_diseases',
    name: 'Diseases of the Liver',
    questions: 10,
    subject: 'Gastro­enterology',
  },
];
