export type TClient = {
    id?: number;
    company_name: string,
    company_url: string,
    company_sub_domain: string,
    address: string,
    phone_number: string,
    phone_code?: string,
    contact_name: string,
    contact_email: string,
    contact_phone_number: string,
    contact_phone_code?: string,
    secondary_contact_name: string,
    secondary_contact_email: string,
    secondary_contact_phone_number: string,
    secondary_contact_phone_code?: string,
    contract_start_date: Date,
    contract_end_date: Date,
    invoice_date: Date,
    invoice_amount: string | undefined,
    referred_by: string,
    special_notes?: string | undefined,
    active: string,
    createdAt?: Date | undefined,
    updatedAt?: Date | undefined,
}

// export type TAddEditClient = {
//     id?: number;
//     company_name: string,
//     company_url: string,
//     company_sub_domain: string,
//     address: string,
//     phone_number: string,
//     phone_code?: string,
//     contact_name: string,
//     contact_email: string,
//     contact_phone_number: string,
//     contact_phone_code?: string,
//     secondary_contact_name: string,
//     secondary_contact_email: string,
//     secondary_contact_phone_number: string,
//     secondary_contact_phone_code?: string,
//     contract_start_date: Date,
//     contract_end_date: Date,
//     invoice_date: Date,
//     invoice_amount: string,
//     referred_by: string,
//     special_notes?: string,
//     active: string,
//     createdAt?: Date | undefined,
//     updatedAt?: Date | undefined,
// }